preset: laravel

enabled:

disabled:
  - length_ordered_imports
  - phpdoc_scalar
  - phpdoc_no_package
  - phpdoc_single_line_var_spacing

linting: true

finder:
  exclude:
    - "tests"
    - "node_modules"
    - "storage"
    - "vendor"
  not-name:
    - "AcceptanceTester.php"
    - "FunctionalTester.php"
    - "UnitTester.php"
    - "*Stub.php"
