preset: laravel

enabled:
#  - phpdoc_annotation_without_dot

disabled:
  - length_ordered_imports
  - phpdoc_scalar
  - phpdoc_no_package

linting: true

finder:
  exclude:
    - "tests"
    - "node_modules"
    - "storage"
    - "vendor"
  not-name:
    - "AcceptanceTester.php"
    - "FunctionalTester.php"
    - "UnitTester.php"
    - "*Stub.php"
